-- Agenda Escolar Digital — esquema PostgreSQL
-- Requiere PostgreSQL 14+
--
-- ► Usar Flyway (recomendado), desde la carpeta api/:
--
--   pnpm db:up          # Postgres local (docker compose)
--   pnpm db:migrate     # V1…V4 + R__triggers
--   pnpm db:seed:dev    # datos demo (solo desarrollo)
--   pnpm db:setup       # migrate + seed-dev
--
-- Migraciones: database/migrations/
--   V1__extensions_and_types.sql
--   V2__tables.sql
--   V3__views.sql
--   V4__seed_iam.sql
--   R__triggers.sql     (repeatable; se reaplica si cambia)
--
-- Referencia Fase 2 (no ejecutar): fase2-comentado.sql
-- Documentación relaciones: relacion.md
