services:
  postgres:
    image: postgres:16-alpine
    container_name: agenda-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda_escolar
    ports:
      - '5434:5432'
    volumes:
      - agenda_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d agenda_escolar']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  agenda_pgdata:
